<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'easyadmin.filter.type.configurator.choice' shared service.

include_once $this->targetDirs[3].'/vendor/easycorp/easyadmin-bundle/src/Form/Type/Configurator/TypeConfiguratorInterface.php';
include_once $this->targetDirs[3].'/vendor/easycorp/easyadmin-bundle/src/Form/Filter/Type/Configurator/ChoiceFilterTypeConfigurator.php';

return $this->privates['easyadmin.filter.type.configurator.choice'] = new \EasyCorp\Bundle\EasyAdminBundle\Form\Filter\Type\Configurator\ChoiceFilterTypeConfigurator();
