<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.u_1UsKg' shared service.

return $this->privates['.service_locator.u_1UsKg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'om' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'passwordEncoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService.php', true],
    'validator' => ['services', 'validator', 'getValidatorService', false],
], [
    'om' => '?',
    'passwordEncoder' => '?',
    'validator' => '?',
]);
