<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.1sq_sD8' shared service.

return $this->privates['.service_locator.1sq_sD8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CompteController::creer' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\DepotController::deposer' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\PartenaireController::createPartenaire' => ['privates', '.service_locator..EwH3.j', 'get_ServiceLocator__EwH3_JService.php', true],
    'App\\Controller\\UserController::register' => ['privates', '.service_locator.u_1UsKg', 'get_ServiceLocator_U1UsKgService.php', true],
    'App\\Controller\\CompteController:creer' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\DepotController:deposer' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\PartenaireController:createPartenaire' => ['privates', '.service_locator..EwH3.j', 'get_ServiceLocator__EwH3_JService.php', true],
    'App\\Controller\\UserController:register' => ['privates', '.service_locator.u_1UsKg', 'get_ServiceLocator_U1UsKgService.php', true],
], [
    'App\\Controller\\CompteController::creer' => '?',
    'App\\Controller\\DepotController::deposer' => '?',
    'App\\Controller\\PartenaireController::createPartenaire' => '?',
    'App\\Controller\\UserController::register' => '?',
    'App\\Controller\\CompteController:creer' => '?',
    'App\\Controller\\DepotController:deposer' => '?',
    'App\\Controller\\PartenaireController:createPartenaire' => '?',
    'App\\Controller\\UserController:register' => '?',
]);
