<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Gd29ivD' shared service.

return $this->privates['.service_locator.Gd29ivD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'entityManager' => ['privates', '.errored..service_locator.Gd29ivD.Doctrine\\ORM\\EntityManager', NULL, 'Cannot autowire service ".service_locator.Gd29ivD": it references class "Doctrine\\ORM\\EntityManager" but no such service exists. Try changing the type-hint to one of its parents: interface "Doctrine\\ORM\\EntityManagerInterface", or interface "Doctrine\\Common\\Persistence\\ObjectManager".'],
], [
    'entityManager' => 'Doctrine\\ORM\\EntityManager',
]);
