<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.QxqSsHw' shared service.

return $this->privates['.service_locator.QxqSsHw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'jwtEncoder' => ['services', 'lexik_jwt_authentication.encoder', 'getLexikJwtAuthentication_EncoderService.php', true],
], [
    'jwtEncoder' => '?',
]);
