<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.vxsbI4Y' shared service.

return $this->privates['.service_locator.vxsbI4Y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CompteController::creer' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\DepotController::deposer' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\OperationsController::operation' => ['privates', '.service_locator.J4Wn4yL', 'get_ServiceLocator_J4Wn4yLService.php', true],
    'App\\Controller\\PartenaireController::createPartenaire' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\PartenaireController::list' => ['privates', '.service_locator.eIEYWuf', 'get_ServiceLocator_EIEYWufService.php', true],
    'App\\Controller\\PartenaireController::update' => ['privates', '.service_locator.fDbIXxi', 'get_ServiceLocator_FDbIXxiService.php', true],
    'App\\Controller\\UserController::login' => ['privates', '.service_locator.QxqSsHw', 'get_ServiceLocator_QxqSsHwService.php', true],
    'App\\Controller\\UserController::register' => ['privates', '.service_locator.2B8PUum', 'get_ServiceLocator_2B8PUumService.php', true],
    'App\\Controller\\CompteController:creer' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\DepotController:deposer' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\OperationsController:operation' => ['privates', '.service_locator.J4Wn4yL', 'get_ServiceLocator_J4Wn4yLService.php', true],
    'App\\Controller\\PartenaireController:createPartenaire' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\PartenaireController:list' => ['privates', '.service_locator.eIEYWuf', 'get_ServiceLocator_EIEYWufService.php', true],
    'App\\Controller\\PartenaireController:update' => ['privates', '.service_locator.fDbIXxi', 'get_ServiceLocator_FDbIXxiService.php', true],
    'App\\Controller\\UserController:login' => ['privates', '.service_locator.QxqSsHw', 'get_ServiceLocator_QxqSsHwService.php', true],
    'App\\Controller\\UserController:register' => ['privates', '.service_locator.2B8PUum', 'get_ServiceLocator_2B8PUumService.php', true],
], [
    'App\\Controller\\CompteController::creer' => '?',
    'App\\Controller\\DepotController::deposer' => '?',
    'App\\Controller\\OperationsController::operation' => '?',
    'App\\Controller\\PartenaireController::createPartenaire' => '?',
    'App\\Controller\\PartenaireController::list' => '?',
    'App\\Controller\\PartenaireController::update' => '?',
    'App\\Controller\\UserController::login' => '?',
    'App\\Controller\\UserController::register' => '?',
    'App\\Controller\\CompteController:creer' => '?',
    'App\\Controller\\DepotController:deposer' => '?',
    'App\\Controller\\OperationsController:operation' => '?',
    'App\\Controller\\PartenaireController:createPartenaire' => '?',
    'App\\Controller\\PartenaireController:list' => '?',
    'App\\Controller\\PartenaireController:update' => '?',
    'App\\Controller\\UserController:login' => '?',
    'App\\Controller\\UserController:register' => '?',
]);
