<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.CiSjE8A' shared service.

return $this->privates['.service_locator.CiSjE8A'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CompteController::creer' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\DepotController::deposer' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\PartenaireController::createPartenaire' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\UserController::register' => ['privates', '.service_locator.2B8PUum', 'get_ServiceLocator_2B8PUumService.php', true],
    'App\\Controller\\CompteController:creer' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\DepotController:deposer' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\PartenaireController:createPartenaire' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\UserController:register' => ['privates', '.service_locator.2B8PUum', 'get_ServiceLocator_2B8PUumService.php', true],
], [
    'App\\Controller\\CompteController::creer' => '?',
    'App\\Controller\\DepotController::deposer' => '?',
    'App\\Controller\\PartenaireController::createPartenaire' => '?',
    'App\\Controller\\UserController::register' => '?',
    'App\\Controller\\CompteController:creer' => '?',
    'App\\Controller\\DepotController:deposer' => '?',
    'App\\Controller\\PartenaireController:createPartenaire' => '?',
    'App\\Controller\\UserController:register' => '?',
]);
