<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'creer_compte' => [[], ['_controller' => 'App\\Controller\\CompteController::creer'], [], [['text', '/api/addcompte']], [], []],
    'depot' => [[], ['_controller' => 'App\\Controller\\DepotController::deposer'], [], [['text', '/api/depot']], [], []],
    'partenaire' => [[], ['_controller' => 'App\\Controller\\PartenaireController::createPartenaire'], [], [['text', '/api/partenaire']], [], []],
    'admin_register' => [[], ['_controller' => 'App\\Controller\\UserController::register'], [], [['text', '/api/inscription']], [], []],
    'api_login' => [[], ['_controller' => 'App\\Controller\\UserController::login'], [], [['text', '/api/login']], [], []],
    'api_profile' => [[], ['_controller' => 'App\\Controller\\UserController::profile'], [], [['text', '/api/profile']], [], []],
    'api_home' => [[], ['_controller' => 'App\\Controller\\UserController::home'], [], [['text', '/api/']], [], []],
    'api_entrypoint' => [['index', '_format'], ['_controller' => 'api_platform.action.entrypoint', '_format' => '', '_api_respond' => 'true', 'index' => 'index'], ['index' => 'index'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', 'index', 'index', true], ['text', '/api']], [], []],
    'api_doc' => [['_format'], ['_controller' => 'api_platform.action.documentation', '_format' => '', '_api_respond' => 'true'], [], [['variable', '.', '[^/]++', '_format', true], ['text', '/api/docs']], [], []],
    'api_jsonld_context' => [['shortName', '_format'], ['_controller' => 'api_platform.jsonld.action.context', '_format' => 'jsonld', '_api_respond' => 'true'], ['shortName' => '.+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '.+', 'shortName', true], ['text', '/api/contexts']], [], []],
    'easyadmin' => [[], ['_controller' => 'EasyCorp\\Bundle\\EasyAdminBundle\\Controller\\AdminController::indexAction'], [], [['text', '/admin/']], [], []],
    'api_logout' => [[], [], [], [['text', '/logout']], [], []],
    'api_login_check' => [[], [], [], [['text', '/api/login']], [], []],
];
