<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEnBeoVs\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEnBeoVs/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEnBeoVs.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEnBeoVs\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEnBeoVs\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'EnBeoVs',
    'container.build_id' => '528a9127',
    'container.build_time' => 1565268936,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEnBeoVs');
