<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA5q1967\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA5q1967/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA5q1967.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA5q1967\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerA5q1967\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'A5q1967',
    'container.build_id' => 'b9f9a04a',
    'container.build_time' => 1565543812,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA5q1967');
